-- =============================================================================
-- 010_extract_boot_ddl_from_app_py_schema_as_code_removal.sql
-- =============================================================================
-- DDL (schemas, tables, columns, indexes, views, triggers, grants) — 82 statements.
--
-- PROVENANCE: extracted MECHANICALLY (python ast.literal_eval) from the
-- `migrations = [...]` list in app.py's run_db_migrations(), which until
-- 2026-07-13 executed this DDL as PYTHON STRINGS at every application boot —
-- schema-as-code, unversioned, forbidden by canonical SQL.1. This is a
-- FAITHFUL, ORDER-PRESERVING extraction (no rewriting), so it is provably
-- equivalent to what the application has actually been executing, INCLUDING the
-- schema/search_path preamble the loop applied around the list.
--
-- Every statement is idempotent (IF NOT EXISTS / OR REPLACE / re-GRANT), so this
-- is a no-op against the live database and builds the schema on a fresh one.
--
-- Do NOT edit this file. Write a NEW numbered migration instead (SQL.1).
-- =============================================================================

-- ---------------------------------------------------------------------------
-- PREAMBLE — REQUIRED CONTEXT (do not remove).
-- Migration 007 split the schema: tables live in dshub / dsapp / dscore, NOT
-- public. The DDL below uses UNQUALIFIED table names, so it only resolves
-- correctly under this search_path. app.py set this on its connection before
-- executing the same statements; a .sql file that omits it silently fails with
-- "relation ... does not exist" (verified 2026-07-13 — the first extraction of
-- this file omitted the preamble and did exactly that).
-- ---------------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS dshub;
CREATE SCHEMA IF NOT EXISTS dsapp;
CREATE SCHEMA IF NOT EXISTS dscore;
CREATE SCHEMA IF NOT EXISTS api;
SET search_path = dshub, dsapp, dscore, public;

ALTER TABLE hubitat_matter_devices ADD COLUMN IF NOT EXISTS commission_attempts INTEGER DEFAULT 0;

ALTER TABLE hubitat_matter_devices ADD COLUMN IF NOT EXISTS last_commission_attempt TIMESTAMPTZ;

ALTER TABLE hubitat_matter_devices ADD COLUMN IF NOT EXISTS last_commission_error TEXT;

CREATE TABLE IF NOT EXISTS matter_device_codes (
            id SERIAL PRIMARY KEY,
            unique_id VARCHAR(128),
            mac VARCHAR(32),
            serial VARCHAR(128),
            device_name VARCHAR(200),
            code_ciphertext BYTEA NOT NULL,
            nonce BYTEA NOT NULL,
            is_factory_code BOOLEAN NOT NULL DEFAULT true,
            source VARCHAR(30) NOT NULL DEFAULT 'commission',
            key_fingerprint VARCHAR(20),
            created_at TIMESTAMPTZ DEFAULT NOW(),
            updated_at TIMESTAMPTZ DEFAULT NOW()
        );

CREATE UNIQUE INDEX IF NOT EXISTS uq_matter_device_codes_unique_id ON matter_device_codes(unique_id) WHERE unique_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_matter_device_codes_mac ON matter_device_codes(mac) WHERE mac IS NOT NULL;

CREATE TABLE IF NOT EXISTS dsapp.panel_devices (
            id SERIAL PRIMARY KEY,
            name VARCHAR(120) NOT NULL,
            kind VARCHAR(20) NOT NULL DEFAULT 'panel',
            token_hash CHAR(64) NOT NULL UNIQUE,
            token_prefix VARCHAR(16),
            scopes TEXT[] NOT NULL DEFAULT ARRAY['panel:read']::TEXT[],
            require_lan BOOLEAN NOT NULL DEFAULT true,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            last_seen_at TIMESTAMPTZ,
            last_seen_ip VARCHAR(64),
            revoked_at TIMESTAMPTZ
        );

CREATE INDEX IF NOT EXISTS idx_panel_devices_active_token ON dsapp.panel_devices(token_hash) WHERE revoked_at IS NULL;

CREATE TABLE IF NOT EXISTS dsapp.panel_preferences (
            id SERIAL PRIMARY KEY,
            profile VARCHAR(60) NOT NULL DEFAULT 'default',
            category VARCHAR(60) NOT NULL,
            value JSONB NOT NULL DEFAULT '{}'::jsonb,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            UNIQUE (profile, category)
        );

CREATE TABLE IF NOT EXISTS device_hub_mapping (
            device_label VARCHAR(200) NOT NULL,
            native_hub_name VARCHAR(100) NOT NULL,
            native_hub_ip VARCHAR(50) NOT NULL,
            native_device_id VARCHAR(50) NOT NULL,
            protocol VARCHAR(30) NOT NULL DEFAULT 'unknown',
            device_type VARCHAR(200),
            mirrors JSONB DEFAULT '{}',
            is_mesh_linked BOOLEAN DEFAULT false,
            last_classified_at TIMESTAMPTZ DEFAULT NOW(),
            PRIMARY KEY (device_label, native_hub_name)
        );

CREATE INDEX IF NOT EXISTS idx_device_hub_mapping_label ON device_hub_mapping(device_label);

CREATE INDEX IF NOT EXISTS idx_device_hub_mapping_hub ON device_hub_mapping(native_hub_name);

CREATE INDEX IF NOT EXISTS idx_device_hub_mapping_protocol ON device_hub_mapping(protocol);

GRANT SELECT, INSERT, UPDATE, DELETE ON device_hub_mapping TO smarthome_anon;

ALTER TABLE event_log ADD COLUMN IF NOT EXISTS hub_ip VARCHAR(50);

ALTER TABLE event_log ADD COLUMN IF NOT EXISTS canonical_device_id BIGINT REFERENCES devices(id);

ALTER TABLE event_log ADD COLUMN IF NOT EXISTS intake_path VARCHAR(20);

ALTER TABLE event_log ADD COLUMN IF NOT EXISTS processing_ms INTEGER;

CREATE INDEX IF NOT EXISTS idx_event_log_canonical ON event_log(canonical_device_id, received_at DESC);

CREATE INDEX IF NOT EXISTS idx_event_log_intake_time ON event_log(intake_path, received_at DESC);

CREATE TABLE IF NOT EXISTS event_routings (
            id           BIGSERIAL PRIMARY KEY,
            event_id     BIGINT NOT NULL REFERENCES event_log(id) ON DELETE CASCADE,
            instance_id  BIGINT REFERENCES app_instances(id) ON DELETE SET NULL,
            enqueued_at  TIMESTAMPTZ DEFAULT NOW(),
            processed_at TIMESTAMPTZ,
            outcome      VARCHAR(30) NOT NULL,
            drop_reason  TEXT
        );

CREATE INDEX IF NOT EXISTS idx_event_routings_event ON event_routings(event_id);

CREATE INDEX IF NOT EXISTS idx_event_routings_instance ON event_routings(instance_id, enqueued_at DESC);

CREATE INDEX IF NOT EXISTS idx_event_routings_outcome ON event_routings(outcome, enqueued_at DESC);

CREATE TABLE IF NOT EXISTS device_commands (
            id                       BIGSERIAL PRIMARY KEY,
            instance_id              BIGINT REFERENCES app_instances(id) ON DELETE SET NULL,
            canonical_device_id      BIGINT REFERENCES devices(id) ON DELETE SET NULL,
            hubitat_device_id        VARCHAR(50),
            hub_ip                   VARCHAR(50),
            command                  VARCHAR(50) NOT NULL,
            arguments                JSONB DEFAULT '[]'::jsonb,
            desired_attribute        VARCHAR(50),
            desired_value            VARCHAR(200),
            triggered_by_event_id    BIGINT REFERENCES event_log(id) ON DELETE SET NULL,
            parent_command_id        BIGINT REFERENCES device_commands(id) ON DELETE SET NULL,
            attempt                  INTEGER DEFAULT 1,
            max_attempts             INTEGER DEFAULT 1,
            issued_at                TIMESTAMPTZ DEFAULT NOW(),
            completed_at             TIMESTAMPTZ,
            outcome                  VARCHAR(30) DEFAULT 'pending',
            final_observed_value     VARCHAR(200),
            verify_retries_used      INTEGER,
            latency_ms               INTEGER,
            error                    TEXT
        );

CREATE INDEX IF NOT EXISTS idx_device_commands_device ON device_commands(canonical_device_id, issued_at DESC);

CREATE INDEX IF NOT EXISTS idx_device_commands_instance ON device_commands(instance_id, issued_at DESC);

CREATE INDEX IF NOT EXISTS idx_device_commands_outcome ON device_commands(outcome, issued_at DESC);

CREATE INDEX IF NOT EXISTS idx_device_commands_trig ON device_commands(triggered_by_event_id);

CREATE INDEX IF NOT EXISTS idx_device_commands_parent ON device_commands(parent_command_id);

CREATE TABLE IF NOT EXISTS instance_state_log (
            id          BIGSERIAL PRIMARY KEY,
            instance_id BIGINT NOT NULL REFERENCES app_instances(id) ON DELETE CASCADE,
            transition  VARCHAR(40) NOT NULL,
            details     JSONB DEFAULT '{}'::jsonb,
            actor       VARCHAR(60),
            occurred_at TIMESTAMPTZ DEFAULT NOW()
        );

CREATE INDEX IF NOT EXISTS idx_instance_state_log_instance ON instance_state_log(instance_id, occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_instance_state_log_transition ON instance_state_log(transition, occurred_at DESC);

CREATE TABLE IF NOT EXISTS mode_change_log (
            id                 BIGSERIAL PRIMARY KEY,
            mode_name          VARCHAR(60) NOT NULL,
            became_active_at   TIMESTAMPTZ DEFAULT NOW(),
            became_inactive_at TIMESTAMPTZ,
            source             VARCHAR(40)
        );

CREATE INDEX IF NOT EXISTS idx_mode_change_log_active ON mode_change_log(became_active_at DESC);

CREATE TABLE IF NOT EXISTS hub_health (
            hub_id                  INTEGER PRIMARY KEY REFERENCES hub_config(id) ON DELETE CASCADE,
            ws_connected            BOOLEAN DEFAULT FALSE,
            ws_connected_since      TIMESTAMPTZ,
            ws_last_event_at        TIMESTAMPTZ,
            ws_last_failure_at      TIMESTAMPTZ,
            ws_last_failure_reason  TEXT,
            ws_consecutive_failures INTEGER DEFAULT 0,
            ws_reconnects_24h       INTEGER DEFAULT 0,
            ws_events_received_24h  BIGINT DEFAULT 0,
            last_reconcile_at       TIMESTAMPTZ,
            last_reconcile_diffs    INTEGER DEFAULT 0,
            updated_at              TIMESTAMPTZ DEFAULT NOW()
        );

ALTER TABLE hub_health ADD COLUMN IF NOT EXISTS platform_version TEXT;

ALTER TABLE hub_health ADD COLUMN IF NOT EXISTS platform_version_seen_at TIMESTAMPTZ;

ALTER TABLE hub_health ADD COLUMN IF NOT EXISTS command_path_ok BOOLEAN;

ALTER TABLE hub_health ADD COLUMN IF NOT EXISTS command_path_contract VARCHAR(10);

ALTER TABLE hub_health ADD COLUMN IF NOT EXISTS command_path_checked_at TIMESTAMPTZ;

ALTER TABLE hub_health ADD COLUMN IF NOT EXISTS command_path_error TEXT;

ALTER TABLE hubitat_matter_devices ADD COLUMN IF NOT EXISTS is_removed BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE hubitat_matter_devices ADD COLUMN IF NOT EXISTS removed_at TIMESTAMPTZ;

GRANT SELECT, INSERT, UPDATE, DELETE ON event_routings TO smarthome_anon;

GRANT SELECT, INSERT, UPDATE, DELETE ON device_commands TO smarthome_anon;

GRANT SELECT, INSERT, UPDATE, DELETE ON instance_state_log TO smarthome_anon;

GRANT SELECT, INSERT, UPDATE, DELETE ON mode_change_log TO smarthome_anon;

GRANT SELECT, INSERT, UPDATE, DELETE ON hub_health TO smarthome_anon;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO smarthome_anon;

CREATE TABLE IF NOT EXISTS system_settings (
            key              VARCHAR(80) PRIMARY KEY,
            value            TEXT NOT NULL,
            value_type       VARCHAR(20) NOT NULL,
            description      TEXT,
            ui_exposed       BOOLEAN DEFAULT TRUE,
            requires_restart BOOLEAN DEFAULT FALSE,
            updated_at       TIMESTAMPTZ DEFAULT NOW()
        );

CREATE TABLE IF NOT EXISTS app_type_settings (
            id               BIGSERIAL PRIMARY KEY,
            app_type_id      INTEGER NOT NULL REFERENCES app_types(id) ON DELETE CASCADE,
            key              VARCHAR(80) NOT NULL,
            value            TEXT NOT NULL,
            value_type       VARCHAR(20) NOT NULL,
            description      TEXT,
            ui_exposed       BOOLEAN DEFAULT TRUE,
            requires_restart BOOLEAN DEFAULT FALSE,
            updated_at       TIMESTAMPTZ DEFAULT NOW(),
            UNIQUE (app_type_id, key)
        );

CREATE INDEX IF NOT EXISTS idx_app_type_settings_type ON app_type_settings(app_type_id);

CREATE TABLE IF NOT EXISTS encrypted_secrets (
            key          VARCHAR(80) PRIMARY KEY,
            ciphertext   BYTEA NOT NULL,
            kek_version  INTEGER NOT NULL DEFAULT 1,
            description  TEXT,
            rotated_at   TIMESTAMPTZ,
            created_at   TIMESTAMPTZ DEFAULT NOW(),
            updated_at   TIMESTAMPTZ DEFAULT NOW()
        );

CREATE TABLE IF NOT EXISTS system_boot_log (
            id             BIGSERIAL PRIMARY KEY,
            boot_at        TIMESTAMPTZ DEFAULT NOW(),
            secrets_source VARCHAR(40),
            kek_version    INTEGER,
            notes          TEXT
        );

CREATE INDEX IF NOT EXISTS idx_system_boot_log_at ON system_boot_log(boot_at DESC);

CREATE TABLE IF NOT EXISTS instance_setting_exceptions (
            id           BIGSERIAL PRIMARY KEY,
            instance_id  BIGINT NOT NULL REFERENCES app_instances(id) ON DELETE CASCADE,
            setting_path VARCHAR(120) NOT NULL,
            reason       TEXT,
            granted_at   TIMESTAMPTZ DEFAULT NOW(),
            UNIQUE (instance_id, setting_path)
        );

CREATE INDEX IF NOT EXISTS idx_ise_instance ON instance_setting_exceptions(instance_id);

GRANT SELECT, INSERT, UPDATE, DELETE ON instance_setting_exceptions TO smarthome_anon;

ALTER TABLE hub_config ADD COLUMN IF NOT EXISTS admin_username VARCHAR(80);

ALTER TABLE hub_config ADD COLUMN IF NOT EXISTS admin_password VARCHAR(200);

ALTER TABLE hub_config ADD COLUMN IF NOT EXISTS admin_creds_index INTEGER;

GRANT SELECT, INSERT, UPDATE, DELETE ON system_settings TO smarthome_anon;

GRANT SELECT, INSERT, UPDATE, DELETE ON app_type_settings TO smarthome_anon;

GRANT SELECT, INSERT, UPDATE, DELETE ON encrypted_secrets TO smarthome_anon;

GRANT SELECT, INSERT, UPDATE, DELETE ON system_boot_log TO smarthome_anon;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO smarthome_anon;

CREATE TABLE IF NOT EXISTS dsapp.samsung_tv_instances (
            id              SERIAL PRIMARY KEY,
            label           VARCHAR(120) NOT NULL,
            tv_ip           VARCHAR(45)  NOT NULL,
            mac_address     VARCHAR(17),
            use_ssl         BOOLEAN      NOT NULL DEFAULT TRUE,
            samsung_name    VARCHAR(120) NOT NULL DEFAULT 'mobius_smart_home',
            app_name        VARCHAR(120) NOT NULL DEFAULT 'Smart Home Controller',
            token           VARCHAR(64),
            callbacks       JSONB        NOT NULL DEFAULT '{}'::jsonb,
            is_enabled      BOOLEAN      NOT NULL DEFAULT TRUE,
            is_paused       BOOLEAN      NOT NULL DEFAULT FALSE,
            pause_reason    VARCHAR(50),
            created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
            updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
            CONSTRAINT samsung_tv_instances_tv_ip_samsung_name_key
                UNIQUE (tv_ip, samsung_name)
        );

CREATE INDEX IF NOT EXISTS idx_samsung_tv_instances_enabled ON dsapp.samsung_tv_instances (is_enabled) WHERE is_enabled;

DROP TRIGGER IF EXISTS update_samsung_tv_instances_updated_at ON dsapp.samsung_tv_instances;

CREATE TRIGGER update_samsung_tv_instances_updated_at BEFORE UPDATE ON dsapp.samsung_tv_instances FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE OR REPLACE VIEW api.samsung_tv_instances AS SELECT * FROM dsapp.samsung_tv_instances;

GRANT SELECT, INSERT, UPDATE, DELETE ON dsapp.samsung_tv_instances TO smarthome_anon;

GRANT SELECT, INSERT, UPDATE, DELETE ON api.samsung_tv_instances   TO smarthome_anon;

GRANT USAGE, SELECT ON SEQUENCE dsapp.samsung_tv_instances_id_seq TO smarthome_anon;

ALTER TABLE dshub.devices ADD COLUMN IF NOT EXISTS is_present boolean NOT NULL DEFAULT true;

CREATE OR REPLACE VIEW api.devices AS SELECT id, hub_ip, hubitat_id, name, label, device_type, protocol, capabilities, attributes, last_synced_at, hub_id, is_name_duplicate, is_present FROM dshub.devices;

CREATE TABLE IF NOT EXISTS dsapp.sonos_speakers (
            ip               varchar(50) PRIMARY KEY,
            room             varchar(120),
            saved_volume     integer,
            persist_volume   boolean NOT NULL DEFAULT false,
            persisted_level  integer,
            updated_at       timestamptz NOT NULL DEFAULT now()
        );

CREATE OR REPLACE VIEW api.sonos_speakers AS SELECT ip, room, saved_volume, persist_volume, persisted_level, updated_at FROM dsapp.sonos_speakers;

CREATE TABLE IF NOT EXISTS dsapp.manual_overrides (
            id            bigserial PRIMARY KEY,
            ts            timestamptz NOT NULL DEFAULT now(),
            instance_id   integer,
            app_type      varchar(60),
            device_id     bigint,
            device_label  varchar(160),
            attribute     varchar(40),
            expected      varchar(40),
            actual        varchar(40),
            location_mode varchar(60),
            context       jsonb,
            cleared_at    timestamptz
        );

CREATE INDEX IF NOT EXISTS idx_manual_overrides_instance ON dsapp.manual_overrides (instance_id, ts DESC);

CREATE OR REPLACE VIEW api.manual_overrides AS SELECT id, ts, instance_id, app_type, device_id, device_label, attribute, expected, actual, location_mode, context, cleared_at FROM dsapp.manual_overrides;

