-- =============================================================================
-- 011_seed_and_backfill_from_app_py_boot.sql
-- =============================================================================
-- DATA: bootstrap seeds + backfills — 11 statements. SQL.1 says data backfills
-- belong in scripts, not migrations; they are kept here (ordered AFTER all DDL)
-- purely to preserve the exact boot behaviour being replaced. Splitting them out
-- is a follow-up refactor, not a silent behaviour change.
--
-- PROVENANCE: extracted MECHANICALLY (python ast.literal_eval) from the
-- `migrations = [...]` list in app.py's run_db_migrations(), which until
-- 2026-07-13 executed this DDL as PYTHON STRINGS at every application boot —
-- schema-as-code, unversioned, forbidden by canonical SQL.1. This is a
-- FAITHFUL, ORDER-PRESERVING extraction (no rewriting), so it is provably
-- equivalent to what the application has actually been executing, INCLUDING the
-- schema/search_path preamble the loop applied around the list.
--
-- Every statement is idempotent (IF NOT EXISTS / OR REPLACE / re-GRANT), so this
-- is a no-op against the live database and builds the schema on a fresh one.
--
-- Do NOT edit this file. Write a NEW numbered migration instead (SQL.1).
-- =============================================================================

-- ---------------------------------------------------------------------------
-- PREAMBLE — REQUIRED CONTEXT (do not remove).
-- Migration 007 split the schema: tables live in dshub / dsapp / dscore, NOT
-- public. The DDL below uses UNQUALIFIED table names, so it only resolves
-- correctly under this search_path. app.py set this on its connection before
-- executing the same statements; a .sql file that omits it silently fails with
-- "relation ... does not exist" (verified 2026-07-13 — the first extraction of
-- this file omitted the preamble and did exactly that).
-- ---------------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS dshub;
CREATE SCHEMA IF NOT EXISTS dsapp;
CREATE SCHEMA IF NOT EXISTS dscore;
CREATE SCHEMA IF NOT EXISTS api;
SET search_path = dshub, dsapp, dscore, public;

INSERT INTO hub_config (hub_name, hub_ip, maker_api_app_number, maker_api_token_env, is_primary) VALUES ('home_1', '<LAN_IP>', '1717', 'HUBITAT_API_TOKEN_OTHER_HUB_1', false) ON CONFLICT (hub_name) DO NOTHING;

INSERT INTO hub_config (hub_name, hub_ip, maker_api_app_number, maker_api_token_env, is_primary) VALUES ('home_2', '<LAN_IP>', '2151', 'HUBITAT_API_TOKEN_OTHER_HUB_2', false) ON CONFLICT (hub_name) DO NOTHING;

INSERT INTO hub_config (hub_name, hub_ip, maker_api_app_number, maker_api_token_env, is_primary) VALUES ('home_3', '<LAN_IP>', '1269', 'HUBITAT_API_TOKEN_OTHER_HUB_3', false) ON CONFLICT (hub_name) DO NOTHING;

INSERT INTO hub_health (hub_id) SELECT id FROM hub_config WHERE is_enabled = TRUE ON CONFLICT (hub_id) DO NOTHING;

INSERT INTO system_settings (key, value, value_type, description, ui_exposed, requires_restart) VALUES
          ('motion_timeout_floor_seconds', '60', 'int',
           'Minimum no-motion timeout in seconds. AML/Fan clamp computed timeouts to this floor unless the instance has bypassTimeoutFloor=true.',
           TRUE, FALSE),
          ('reconcile_interval_secs', '60', 'int', 'Normal reconcile-poll cadence.', TRUE, FALSE),
          ('reconcile_aggressive_secs', '10', 'int', 'Aggressive reconcile cadence after recent hub WS failure.', TRUE, FALSE),
          ('reconcile_aggressive_window_secs', '300', 'int', 'How recently a hub WS failure must have occurred to engage aggressive reconcile.', TRUE, FALSE),
          ('eventsocket_watchdog_secs', '120', 'int', 'Recycle WS connection if no events arrive within this window.', TRUE, FALSE),
          ('device_cmd_verify_retries', '3', 'int', 'Polls per command-send attempt to verify state.', TRUE, FALSE),
          ('device_cmd_verify_delay', '1.0', 'float', 'Seconds between verify polls.', TRUE, FALSE),
          ('device_cmd_operation_retries', '2', 'int', 'Full send+verify cycles before giving up.', TRUE, FALSE),
          ('aml_init_master_delay_seconds', '5', 'int', 'AML initialize() schedules its first master() run after this many seconds. Short delay lets in-flight motion events arrive first.', TRUE, FALSE),
          ('aml_periodic_eval_interval_seconds', '60', 'int', 'Defensive: every AML instance runs master() at this cadence regardless of events. Minimum 10s.', TRUE, FALSE),
          ('timezone', 'America/New_York', 'string', 'IANA timezone name. Hub-derived: refreshed hourly from /location/list/data on every enabled hub. UI editing is advisory — the next refresh cycle overrides. DB stays in UTC; this is applied to the app container at boot for log timestamps.', TRUE, FALSE),
          ('hub_tz_inconsistency', 'false', 'bool', 'Set to TRUE by the hub-TZ refresher when enabled hubs report disagreeing time zones. Dashboard surfaces this as a warning so the user can fix the outlier from the Hubitat UI.', TRUE, FALSE),
          ('hub_tz_breakdown', '{}', 'string', 'JSON object {hub_name: tz_or_status} from the most recent hub-TZ refresh. Populated by services.hub_tz_resolver. Values are Windows-style TZ strings, "unreachable", or "unmapped:<tz>".', TRUE, FALSE),
          ('colorblind_mode', 'false', 'bool', 'Use a colorblind-safe (Okabe-Ito) palette in charts and accent colors. Designed for protanopia / deuteranopia / tritanopia.', TRUE, FALSE),
          ('eventsocket_enabled', 'true', 'bool', 'Master switch for Hubitat eventsocket WS intake. Requires app restart.', TRUE, TRUE),
          ('reconcile_poll_enabled', 'true', 'bool', 'Reconcile poll on/off. Requires app restart.', TRUE, TRUE),
          ('device_commands_logging', 'true', 'bool', 'Two-phase device_commands logging. Requires app restart.', TRUE, TRUE),
          ('webhook_intake_enabled', 'false', 'bool', 'Legacy webhook intake — rollback escape hatch.', TRUE, TRUE),
          ('maker_api_enabled', 'false', 'bool', 'When TRUE: reconcile poll + commands + verify use Maker API (legacy path). When FALSE (default 2026-05-17): all three use the Hubitat admin API directly — bypasses Maker entirely. Toggle on /hubs page. Eventsocket WS handles inbound events regardless.', TRUE, FALSE)
        ON CONFLICT (key) DO NOTHING;

UPDATE dsapp.app_instances ai SET settings = ai.settings || jsonb_build_object('keepOffEnabled', true) WHERE ai.app_type_id = 1   AND jsonb_array_length(coalesce(ai.device_selections->'keep_off_switches', '[]'::jsonb)) > 0   AND NOT (ai.settings ? 'keepOffEnabled');

UPDATE dsapp.app_instances ai SET settings = ai.settings || jsonb_build_object('keepOnEnabled', true) WHERE ai.app_type_id = 1   AND jsonb_array_length(coalesce(ai.device_selections->'keep_on_switches', '[]'::jsonb)) > 0   AND NOT (ai.settings ? 'keepOnEnabled');

WITH all_modes AS (SELECT jsonb_agg(mode_name) AS modes FROM dshub.location_modes) UPDATE dsapp.app_instances ai SET settings = ai.settings || jsonb_build_object('keepOffModes', (SELECT modes FROM all_modes)) WHERE ai.app_type_id = 1   AND jsonb_array_length(coalesce(ai.device_selections->'keep_off_switches', '[]'::jsonb)) > 0   AND jsonb_array_length(coalesce(ai.settings->'keepOffModes', '[]'::jsonb)) = 0;

WITH all_modes AS (SELECT jsonb_agg(mode_name) AS modes FROM dshub.location_modes) UPDATE dsapp.app_instances ai SET settings = ai.settings || jsonb_build_object('keepOnModes', (SELECT modes FROM all_modes)) WHERE ai.app_type_id = 1   AND jsonb_array_length(coalesce(ai.device_selections->'keep_on_switches', '[]'::jsonb)) > 0   AND jsonb_array_length(coalesce(ai.settings->'keepOnModes', '[]'::jsonb)) = 0;

INSERT INTO dshub.system_settings (key, value, value_type, description, ui_exposed, requires_restart) VALUES ('matter_primary_enabled', 'false', 'bool', 'When TRUE: commands for devices commissioned to our matter-server (and online) go DIRECTLY over Matter (faster + independent of Hubitat''s Matter bridge); Hubitat is the fallback. Default false.', true, false) ON CONFLICT (key) DO NOTHING;

NOTIFY pgrst, 'reload schema';

-- Make PostgREST see columns added above immediately (app.py did this last).
NOTIFY pgrst, 'reload schema';
